services:
  - type: web
    name: ssuportlog
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && (test -d repo/.git || git clone https://github.com/ssu-student-union/ssuport-frontend repo)
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: BASIC_AUTH_USERNAME
        sync: false
      - key: BASIC_AUTH_PASSWORD
        sync: false
